### ISSUE TITLE
Make File Structure

### ISSUE THREAD

**Issue by dborncamp** [spacetelescope/ACSRefPipe#2]
We need to make the file structure for the repository. I think it should look like:

+ ACSRefPipe/
    |--> download/
    |--> bias/
    |--> dark/
    |--> sink/
    |--> history/
    |--> stats/
    |--> verify/
    |--> util/
    |--> doc/

With each being its own module and having its own tests.

@nmiles2718 @tddesjardins any comments/thoughts?

**Comment by nmiles2718** [comment]
What is going to be the difference between verify/ and util/ @dborncamp ?

**Comment by dborncamp** [comment]
Verify will contain everything that we need to certify or test the reference files. I imagine that util will contain any general utilities that we end up using.

**Comment by tddesjardins** [comment]
This looks good to me. I mean, we can always modify it later if we deem it really necessary, but for now this is straightforward.
