### ISSUE TITLE
Look into MAST API For Downloads

### ISSUE THREAD

**Issue by dborncamp** [spacetelescope/acsrefpipe#8]
Look into using the MAST API for all of our downloads and anneal detection. This does not seem to do everything at the moment but Tom and Clara seem to think that they can make it do what we want. Try to do what we need first and let them know exactly what we need.

**Comment by tddesjardins** [comment]
Using astroquery for all of our MAST interface/download needs now. For anneal detection, we are still parsing the XML visit status information.
